### ISSUE TITLE
Remove SynpufResults archive from results for PLE

### ISSUE THREAD

**Issue by spbima** [OHDSI/ArachneExecutionEngine#193]
Remove SynpufResults archive from results for PLE

**Comment by pavgra** [comment]
I assume this is a naming issue. Not the redundant folder issue

**Comment by AntonStepanof** [comment]
Reproduced that locally:
Adding results to zip file
Results are ready for sharing at:/private/var/folders/yx/57l0v0sd16xfn5kvnrk0rjkr0000gn/T/1557151757057-0/results/export/ResultsSynpuf.zip

At code(StudyProtocolSandbox/Export.R) it looks like that:
  ParallelLogger::logInfo("Adding results to zip file")
  zipName <- file.path(exportFolder, paste0("Results", databaseId, ".zip"))

So Synpuf here is stands for databaseId. Doesn't look like a problem
