### ISSUE TITLE
Error during execution of ple

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/ArachneExecutionEngine#213]
Execution engine returns error:
Thread 1 returns error: "could not find function "prepareKaplanMeier"" when using argument(s): list(strataFile = "StratPop_l1_s1_p1_t180_c181_s1_o182.rds", studyPopFile = "StudyPop_l1_s1_t180_c181_o182.rds", targetId = 180, comparatorId = 181, outcomeId = 182, analysisId = 1),/tmp/1559653889913-0/results,/tmp/1559653889913-0/results/export/temp,SYNPUF110K-new,5

Design
[celecoxib.zip](https://github.com/OHDSI/ArachneExecutionEngine/files/3260834/celecoxib.zip)

Results
[estimation-analysis-results-3147.zip](https://github.com/OHDSI/ArachneExecutionEngine/files/3261671/estimation-analysis-results-3147.zip)

**Comment by pavgra** [comment]
The actual problem is in https://github.com/OHDSI/WebAPI/issues/1180
