### ISSUE TITLE
Instructions on how to execute a custom study package 

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/ArachneExecutionEngine#307]
Suppose I have a custom R package i like to send to data partners that i like them to run with Data Node.

What is the wrapper code that is needed to allow the Execution engine to execute the code.

- Is there a standard R file that is run?
- How  should the logging be arranged?
- Is there a predefined folder structure
- What are the parameters you should use? are these in a local Renviron?

What are the specifications of the code to produce the output of the study,
- Does this need to have a specific name?
- Should it contain prespecified  output (like all the package versions?)
- Etc

The execution engine contains certain versions of all the OHDSI package is that correct? If so which versions are in? 
Is it possible to install packages on the fly in the execution engine session for example by using the Renv package?

What would be helpful is some information about this on a wiki and have a example folder in this repo with a skeleton.

Any ideas? Thanks

**Comment by PRijnbeek** [comment]
I see this in the code https://github.com/OHDSI/ArachneExecutionEngine/blob/8ce4c18a0e4184cac21b4dd18a92b9c4d2d87d54/install/win/libs/libs_part2.r#L6 

Why is this? Is the execution engine installing this study? 

I see all the other packages that are being installed in the libs_partx.r files. Does this mean these are all available in the docker? Does it mean that data partners can be on different versions still (because these are installed from the latest master instead of from the latest release which is not yet the same unfortunately in some of the packages).

**Comment by PRijnbeek** [comment]
This comment from 4 years ago is still open but still relevant.

Can instructions be added on how to make your own execution environment from my own R environment with installed R packages? or is this already somewhere else for the new Data Node which allows for different environments maybe?

**Comment by PRijnbeek** [comment]
@ablack3 are you able to make our own DARWIN Execution Environment? if so let's talk about this. We need instructions for our development team on how to do that.

**Comment by konstjar** [comment]
The documentation is available in ARACHNE repo:

- [R Code Development](https://github.com/OHDSI/Arachne/wiki/R-Code-Development)
- [R Environment Development](https://github.com/OHDSI/Arachne/wiki/R-Environment-Development)
