### ISSUE TITLE
Execution fails in Docker mode when there is no connection to the Internet

### ISSUE THREAD

**Issue by konstjar** [OHDSI/ArachneExecutionEngine#374]
- Docker mode enabled
- Docker image of the R runtime was imported in advance
- There is no Internet available on the host
- When analysis starts, the code tries to pull image as new and throws the error.

Expectations:
- If image exists and pull fails, analysis should be started on existing image.

**Comment by ablack3** [comment]
see https://github.com/OHDSI/ArachneExecutionEngine/blob/81ce125f5b44dafda4c87bd2fbc3acb2b8477a7f/engine/src/main/java/com/odysseusinc/arachne/executionengine/execution/r/DockerService.java#L146

**Comment by ablack3** [comment]
Steps to reproduce:


Create a text file called main.R with one line `print('it works')`

<img width="300" alt="image" src="https://github.com/OHDSI/ArachneExecutionEngine/assets/10227522/0417c85d-10b8-4229-ba79-d9c57e312540">


Put this file in a folder and zip that folder

<img width="773" alt="image" src="https://github.com/OHDSI/ArachneExecutionEngine/assets/10227522/74bd5bdf-805a-440e-9cb1-54575346834b">


<img width="502" alt="image" src="https://github.com/OHDSI/ArachneExecutionEngine/assets/10227522/eac99c3b-e8f1-4f07-8eba-09002dbe93d5">


Uploade the zip file to Arachne datanode. Select the default runtime.

<img width="690" alt="image" src="https://github.com/OHDSI/ArachneExecutionEngine/assets/10227522/e2e1477e-fe6b-4bda-b9a4-c0a13b198217">

Before you submit your analysis turn off internet access on your computer.

**Comment by konstjar** [comment]
Resolved in v2.1.0
